name: Continuous Integration with Maven on Linux

on:
  push:
  pull_request: 
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include:
         - java: 11
           maven-args: "-Pjacoco -DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"
         - java: 17
        
    name: Build with Java ${{matrix.java}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml', '**/*.yml')}}
        restore-keys: ${{runner.os}}-m2-
    - name: Build with Maven
      run: mvn verify ${{matrix.maven-args}}
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_TOKEN}}
      working-directory: com.giulia.giamberini.match